---
title: "Diabetes EDA"
author: "Robert Berini"
format: html
editor: visual
execute: 
  warning: false
  message: false
---

## Load required packages

```{r}
library(conflicted)
library(skimr)
library(psych)
library(tidyverse)

conflicts_prefer(dplyr::lag)
conflicts_prefer(dplyr::filter)

options(scipen = 999, digits = 2)
```

## Read data

```{r}
diabetes_raw <- read_csv("data/diabetes_binary_health_indicators_BRFSS2015.csv")
```

## Check and manipulate the data

Explore columns names, column types, and values.

```{r}
glimpse(diabetes_raw)
```

Check for any missing values.

```{r}
diabetes_raw |>
  skim() |>
  focus(n_missing, complete_rate, numeric.hist)
```

Reassign column types

```{r}
#consistent with social science practices, treating GenHlth Likert scale as an interval scale
true_numeric_cols <- c("BMI", "GenHlth", "MentHlth", "PhysHlth")
multi_fac_cols <- c("Age", "Education", "Income")
```

```{r}
diabetes <-
  diabetes_raw |>
  rename(Diabetes = Diabetes_binary) |>
  mutate(Age = factor(Age, 
                      levels = 1:13, 
                      labels = c("Age 18 - 24", "Age 25 to 29", "Age 30 to 34", 
                                 "Age 35 to 39", "Age 40 to 44", "Age 45 to 49", 
                                 "Age 50 to 54", "Age 55 to 59", "Age 60 to 64", 
                                 "Age 65 to 69", "Age 70 to 74", "Age 75 to 79", 
                                 "Age 80 or older"),
                      ordered = T)) |>
  mutate(Education = factor(Education, 
                            levels = 1:6, 
                            labels = c("No school or only kindergarten", 
                                       "Elementary", 
                                       "Some high school", 
                                       "High school graduate", 
                                       "Some college or technical school", 
                                       "College graduate"),
                            ordered = T)) |>
  mutate(Income = factor(Income, 
                         levels = 1:8, 
                         labels = c("Less than $10,000", 
                                    "$10,000 to less than $15,000", 
                                    "$15,000 to less than $20,000", 
                                    "$20,000 to less than $25,000", 
                                    "$25,000 to less than $35,000", 
                                    "$35,000 to less than $50,000", 
                                    "$50,000 to less than $75,000", 
                                    "$75,000 or more"),
                         ordered = T))|>
  mutate(Sex = factor(as.numeric(Sex), levels = c(0, 1), labels = c("Female", "Male"))) |>
  mutate(across(
    .cols = !c(Sex, true_numeric_cols, multi_fac_cols),
    .fns = ~ factor(as.numeric(.x), levels = c(0, 1), labels = c("No", "Yes"))
  ))
```

```{r}
glimpse(diabetes)
```

Generate basic summary statistics for numeric columns and check the unique values for the categorical variables.

```{r}
diabetes |>
  select(where(is.numeric)) |>
  describe()
```

```{r}
diabetes |>
  select(where(is.factor)) |>
  summary(maxsum = Inf)
```

Save manipulated data set

```{r}
saveRDS(diabetes, "data/diabetes.rds")
```

## EDA
