# Generated by the vetiver package; edit with care

library(pins)
library(plumber)
library(rapidoc)
library(vetiver)
b <- board_connect(auth = "envvar")
v <- vetiver_pin_read(b, "rmberin2@ncsu.edu/diabetes-rf", version = "159")

#* @plumber
function(pr) {
    pr %>% vetiver_api(v)
}
